/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package id.ac.unikom.adsi.ekostan;

import id.ac.unikom.adsi.ekostan.utility.DatabaseConnectivity;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ButtonModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author reyhan
 */
public final class FormKamar extends javax.swing.JDialog {

    /**
     * Creates new form FormKamar
     * @param parent
     * @param modal
     */
    public FormKamar(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        tampil_tabel_kamar();
        tampil_tabel_cari_kamar();
        delete.setEnabled(false);
    }
    
    public void tampil_tabel_cari_kamar(){
        Object []baris = {"Nomor Kamar","Harga","Status"};
        tabmode = new DefaultTableModel(null, baris);
        tabel_cari_kamar.setModel(tabmode);
        Connection conn = DatabaseConnectivity.getConnection();
        try {
            String sql = "select * from kamar order by no_kamar asc";
            java.sql.Statement stat = conn.createStatement();
            java.sql.ResultSet hasil = stat.executeQuery(sql);
            while (hasil.next()){
                String no_kamar = hasil.getString("no_kamar");
                String harga = hasil.getString("harga");
                String status = hasil.getString("status");
                String[] data = {no_kamar,harga,status};
                tabmode.addRow(data);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Menampilkan data GAGAL","Informasi", JOptionPane.INFORMATION_MESSAGE);
        }
    }
    
    public void reset(){
        text_no_kamar.setText("");
        text_harga.setText("");
    }    
    
    private DefaultTableModel tabmode;
    
    public void tampil_tabel_kamar(){
        Object []baris = {"Nomor Kamar","Harga","Status"};
        tabmode = new DefaultTableModel(null, baris);
        tabel_kamar.setModel(tabmode);
        Connection conn = DatabaseConnectivity.getConnection();
        try {
            String sql = "select * from kamar order by no_kamar asc";
            java.sql.Statement stat = conn.createStatement();
            java.sql.ResultSet hasil = stat.executeQuery(sql);
            while (hasil.next()){
                String no_kamar = hasil.getString("no_kamar");
                String harga = hasil.getString("harga");
                String status = hasil.getString("status");
                String[] data = {no_kamar,harga,status};
                tabmode.addRow(data);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Menampilkan data GAGAL","Informasi", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        button_status = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        text_no_kamar = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        text_harga = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        radio_kosong = new javax.swing.JRadioButton();
        radio_terisi = new javax.swing.JRadioButton();
        delete = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        simpan = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabel_kamar = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_cari_kamar = new javax.swing.JTable();
        text_cari_kamar = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Kamar");

        jTabbedPane2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane2MouseClicked(evt);
            }
        });

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Data Kamar"));

        jLabel2.setText("No. Kamar");

        jLabel3.setText("Harga Sewa");

        jLabel4.setText("/ Bulan");

        jLabel7.setText("Status");

        button_status.add(radio_kosong);
        radio_kosong.setText("Kosong");

        button_status.add(radio_terisi);
        radio_terisi.setText("Terisi");

        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        simpan.setText("Simpan");
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(text_harga, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                            .addComponent(text_no_kamar)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(radio_kosong)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(radio_terisi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(simpan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(delete, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)))
                .addGap(5, 5, 5)
                .addComponent(jLabel4)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_no_kamar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_harga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(radio_kosong, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radio_terisi, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(simpan)
                    .addComponent(cancel)
                    .addComponent(delete))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Tabel Data Kamar"));

        tabel_kamar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel_kamar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_kamarMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabel_kamar);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 577, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Data Kamar", jPanel2);

        tabel_cari_kamar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabel_cari_kamar);

        text_cari_kamar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                text_cari_kamarKeyPressed(evt);
            }
        });

        jLabel8.setText("Cari Data Kamar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 894, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(text_cari_kamar, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_cari_kamar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(238, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Cari Data", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTabbedPane2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane2MouseClicked
        // TODO add your handling code here:
        tampil_tabel_kamar();
        tampil_tabel_cari_kamar();
    }//GEN-LAST:event_jTabbedPane2MouseClicked

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        // TODO add your handling code here:
        String no_kamar,harga_sewa,status;
        int kode_buku1;
        no_kamar = text_no_kamar.getText();
        harga_sewa = text_harga.getText();
        String sub_nomor = no_kamar.substring(0,1);
        String sub_nol = no_kamar.substring(1,2);
        String sub_nol1 = no_kamar.substring(2,3);
        String sub_nol2 = no_kamar.substring(3,4);
        String sub_nol3 = no_kamar.substring(4,5);
        int panjang = no_kamar.length();
        
        
        if(radio_terisi.isSelected()){
            status = radio_terisi.getText();
        }else{
            status = radio_kosong.getText();            
        }
        Connection conn = DatabaseConnectivity.getConnection();
        
        if(sub_nomor.compareTo("K")!=0){
            JOptionPane.showMessageDialog(null, "Format NOMOR KAMAR salah!","Informasi", JOptionPane.INFORMATION_MESSAGE);
            text_no_kamar.requestFocus();
        }else if(panjang<5 || panjang>5){
            JOptionPane.showMessageDialog(null, "Format NOMOR KAMAR salah!","Informasi", JOptionPane.INFORMATION_MESSAGE);
            text_no_kamar.requestFocus();
        }else if(sub_nol.compareTo("0")!=0 && sub_nol.compareTo("1")!=0 && sub_nol.compareTo("2")!=0 && sub_nol.compareTo("3")!=0 && sub_nol.compareTo("4")!=0 && sub_nol.compareTo("5")!=0 && sub_nol.compareTo("6")!=0 && sub_nol.compareTo("7")!=0 && sub_nol.compareTo("8")!=0 && sub_nol.compareTo("9")!=0){   
            JOptionPane.showMessageDialog(null, "Format NOMOR KAMAR salah!","Informasi", JOptionPane.INFORMATION_MESSAGE);
            text_no_kamar.requestFocus();
        }else if(sub_nol1.compareTo("0")!=0 && sub_nol1.compareTo("1")!=0 && sub_nol1.compareTo("2")!=0 && sub_nol1.compareTo("3")!=0 && sub_nol1.compareTo("4")!=0 && sub_nol1.compareTo("5")!=0 && sub_nol1.compareTo("6")!=0 && sub_nol1.compareTo("7")!=0 && sub_nol1.compareTo("8")!=0 && sub_nol1.compareTo("9")!=0){   
            JOptionPane.showMessageDialog(null, "Format NOMOR KAMAR salah!","Informasi", JOptionPane.INFORMATION_MESSAGE);
            text_no_kamar.requestFocus();
        }else if(sub_nol2.compareTo("0")!=0 && sub_nol2.compareTo("1")!=0 && sub_nol2.compareTo("2")!=0 && sub_nol2.compareTo("3")!=0 && sub_nol2.compareTo("4")!=0 && sub_nol2.compareTo("5")!=0 && sub_nol2.compareTo("6")!=0 && sub_nol2.compareTo("7")!=0 && sub_nol2.compareTo("8")!=0 && sub_nol2.compareTo("9")!=0){   
            JOptionPane.showMessageDialog(null, "Format NOMOR KAMAR salah!","Informasi", JOptionPane.INFORMATION_MESSAGE);
            text_no_kamar.requestFocus();
        }else if(sub_nol3.compareTo("0")!=0 && sub_nol3.compareTo("1")!=0 && sub_nol3.compareTo("2")!=0 && sub_nol3.compareTo("3")!=0 && sub_nol3.compareTo("4")!=0 && sub_nol3.compareTo("5")!=0 && sub_nol3.compareTo("6")!=0 && sub_nol3.compareTo("7")!=0 && sub_nol3.compareTo("8")!=0 && sub_nol3.compareTo("9")!=0){   
            JOptionPane.showMessageDialog(null, "Format NOMOR KAMAR salah!","Informasi", JOptionPane.INFORMATION_MESSAGE);
            text_no_kamar.requestFocus();
        }else if (no_kamar.compareTo("")==0){
            JOptionPane.showMessageDialog(null, "Silahkan isi NOMOR KAMAR!","Informasi", JOptionPane.INFORMATION_MESSAGE);
            text_no_kamar.requestFocus();
        }else if (harga_sewa.compareTo("")==0){
            JOptionPane.showMessageDialog(null, "Silahkan isi HARGA SEWA!","Informasi", JOptionPane.INFORMATION_MESSAGE);
            text_harga.requestFocus();
        }else{
            try {
                String sql = "insert into kamar values (?,?,?)";
                PreparedStatement stat = (PreparedStatement) conn.prepareStatement(sql);
                stat.setString(1, no_kamar);
                stat.setString(2, harga_sewa);
                stat.setString(3, status);
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "Menyimpan data BERHASIL","Informasi", JOptionPane.INFORMATION_MESSAGE);
                reset();
                tampil_tabel_kamar();
            } catch (SQLException | HeadlessException e) {
                JOptionPane.showMessageDialog(null, "Menyimpan data GAGAL","Informasi", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_simpanActionPerformed

    private void tabel_kamarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_kamarMouseClicked
        // TODO add your handling code here:
        int baris = tabel_kamar.getSelectedRow();
        text_no_kamar.setText((String)tabel_kamar.getValueAt(baris, 0));
        text_harga.setText((String)tabel_kamar.getValueAt(baris, 1));
        cancel.setEnabled(true);
        simpan.setEnabled(false);
        delete.setEnabled(true);
        text_no_kamar.setEnabled(false);
        text_harga.setEnabled(false);
        radio_kosong.setEnabled(false);
        radio_terisi.setEnabled(false);
    }//GEN-LAST:event_tabel_kamarMouseClicked

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // TODO add your handling code here:
        cancel.setEnabled(true);
        simpan.setEnabled(true);
        delete.setEnabled(false);
        text_no_kamar.setEnabled(true);
        text_harga.setEnabled(true);
        radio_kosong.setEnabled(true);
        radio_terisi.setEnabled(true);
        text_no_kamar.setText("");
        text_harga.setText("");
        radio_kosong.setText("Kosong");
        radio_terisi.setText("Terisi");
    }//GEN-LAST:event_cancelActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        int baris = tabel_kamar.getSelectedRow();
        String no_kamar = tabmode.getValueAt(baris, 0).toString();
        int ok=JOptionPane.showConfirmDialog(null,"Apakah Anda yakin ingin menghapus data buku dengan nomor kamar : "+no_kamar+"?","Konfirmasi",JOptionPane.YES_NO_OPTION);
        if(ok==0){
            try{
                //panggil method koneksi
                Connection conn = DatabaseConnectivity.getConnection();
                String sql="delete from kamar where no_kamar='"+no_kamar+"'";
                Statement st = conn.createStatement();
                st.executeUpdate(sql);
                JOptionPane.showMessageDialog(null,"Data Berhasil di hapus");
                tampil_tabel_kamar();
                reset();
                delete.setEnabled(false);
                simpan.setEnabled(true);
                text_no_kamar.setEnabled(true);
                text_harga.setEnabled(true);
                radio_kosong.setEnabled(true);
                radio_terisi.setEnabled(true);
            }catch(SQLException | HeadlessException e){
                JOptionPane.showMessageDialog(null,"Data Gagal di hapus");
            }
        }
    }//GEN-LAST:event_deleteActionPerformed

    private void text_cari_kamarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_cari_kamarKeyPressed
        // TODO add your handling code here:
        String cari = text_cari_kamar.getText();
        Object []baris = {"Nomor Kamar","Harga","Status"};
        tabmode = new DefaultTableModel(null, baris);
        tabel_cari_kamar.setModel(tabmode);

        //panggil method koneksi
        Connection conn = DatabaseConnectivity.getConnection();

        //untuk menampilkan di table
        try{
            String sql="Select * from kamar where "
                    + "no_kamar like '%"+cari+"%' "
                    + "OR harga like '%"+cari+"%' "
                    + "OR status like '%"+cari+"%' "
                    + "order by no_kamar asc";
            java.sql.Statement stmt=conn.createStatement();
            java.sql.ResultSet rslt=stmt.executeQuery(sql);
            while(rslt.next()){
                String no_kamar = rslt.getString("no_kamar");
                String harga = rslt.getString("harga");
                String status = rslt.getString("status");
                String[] dataField={no_kamar,harga,status};
                tabmode.addRow(dataField);
            }
        }
        catch(Exception ex){
        }
    }//GEN-LAST:event_text_cari_kamarKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormKamar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormKamar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormKamar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormKamar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FormKamar dialog = new FormKamar(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup button_status;
    private javax.swing.JButton cancel;
    private javax.swing.JButton delete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JRadioButton radio_kosong;
    private javax.swing.JRadioButton radio_terisi;
    private javax.swing.JButton simpan;
    private javax.swing.JTable tabel_cari_kamar;
    private javax.swing.JTable tabel_kamar;
    private javax.swing.JTextField text_cari_kamar;
    private javax.swing.JTextField text_harga;
    private javax.swing.JTextField text_no_kamar;
    // End of variables declaration//GEN-END:variables
}
