/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package id.ac.unikom.adsi.ekostan;

import id.ac.unikom.adsi.ekostan.utility.DatabaseConnectivity;
import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.Calendar;

/**
 *
 * @author reyhan
 */
public final class FormPenyewaan extends javax.swing.JDialog {

    /**
     * Creates new form FormPenyewaan
     * @param parent
     * @param modal
     */
    public FormPenyewaan(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        tampil_tabel_penyewaan();
        tampil_tabel_cari_penyewaan();
        text_no_transaksi.setEnabled(false);
        text_nama_penyewa.setEnabled(false);
        text_id_penyewa.setEnabled(false);
        text_no_kamar.setEnabled(false);
        text_status.setEnabled(false);
        text_tanggal_sewa.setEnabled(false);
        text_harga.setEnabled(false);
        text_uang_bayar.setEnabled(false);
        text_kembalian.setEnabled(false);
        simpan.setEnabled(false);
        cancel.setEnabled(false);
        delete.setEnabled(false);
        cetak.setEnabled(true);
    }
    
    public void tampil_tabel_cari_penyewaan(){
        Object []baris = {"No. Transaksi","Id Penyewa","Nama Penyewa","No. Kamar","Tanggal Sewa","Harga Sewa"};
        tabmode = new DefaultTableModel(null, baris);
        tabel_cari_penyewaan.setModel(tabmode);
        Connection conn = DatabaseConnectivity.getConnection();
        try {
            String sql = "select * from penyewaan order by no_transaksi asc";
            java.sql.Statement stat = conn.createStatement();
            java.sql.ResultSet hasil = stat.executeQuery(sql);
            while (hasil.next()){
                String no_transaksi = hasil.getString("no_transaksi");
                String id_penyewa = hasil.getString("id_penyewa");
                String nama_penyewa = hasil.getString("nama_penyewa");
                String no_kamar = hasil.getString("no_kamar");
                String tanggal_sewa = hasil.getString("tanggal_sewa"); 
                String total_bayar = hasil.getString("total_bayar");
                String[] data = {no_transaksi, id_penyewa, nama_penyewa, no_kamar, tanggal_sewa, total_bayar};
                tabmode.addRow(data);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Menampilkan data gagal...","Informasi", JOptionPane.INFORMATION_MESSAGE);
        }
    }
    
    public void tampil_tabel_penyewaan(){
        Object []baris = {"No. Transaksi","Id Penyewa","Nama Penyewa","No. Kamar","Tanggal Sewa","Harga Sewa"};
        tabmode = new DefaultTableModel(null, baris);
        tabel_penyewaan.setModel(tabmode);
        Connection conn = DatabaseConnectivity.getConnection();
        try {
            String sql = "select * from penyewaan order by no_transaksi asc";
            java.sql.Statement stat = conn.createStatement();
            java.sql.ResultSet hasil = stat.executeQuery(sql);
            while (hasil.next()){
                String no_transaksi = hasil.getString("no_transaksi");
                String id_penyewa = hasil.getString("id_penyewa");
                String nama_penyewa = hasil.getString("nama_penyewa");
                String no_kamar = hasil.getString("no_kamar");
                String tanggal_sewa = hasil.getString("tanggal_sewa"); 
                String total_bayar = hasil.getString("total_bayar");
                String[] data = {no_transaksi, id_penyewa, nama_penyewa, no_kamar, tanggal_sewa, total_bayar};
                tabmode.addRow(data);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Menampilkan data gagal...","Informasi", JOptionPane.INFORMATION_MESSAGE);
        }
    }
    
    public void reset(){
        text_no_transaksi.setText("");
        text_nama_penyewa.setText("");
        text_id_penyewa.setText("");
        text_no_kamar.setText("");
        text_status.setText("");
        text_harga.setText("");
        text_uang_bayar.setText("");
        text_kembalian.setText("");
        text_tanggal_sewa.setDate(null);
    }
    
    private DefaultTableModel tabmode;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        text_dummy = new javax.swing.JTextField();
        text_dummy1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        text_no_transaksi = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        text_kembalian = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        text_tanggal_sewa = new com.toedter.calendar.JDateChooser();
        jLabel12 = new javax.swing.JLabel();
        text_nama_penyewa = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        text_uang_bayar = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        text_no_kamar = new javax.swing.JTextField();
        text_id_penyewa = new javax.swing.JTextField();
        simpan = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        text_harga = new javax.swing.JTextField();
        cetak = new javax.swing.JButton();
        tambah = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        text_status = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabel_penyewaan = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_cari_penyewaan = new javax.swing.JTable();
        text_cari_penyewaan = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Penyewaan");

        jTabbedPane2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane2MouseClicked(evt);
            }
        });

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Data Penyewaan"));

        text_no_transaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_no_transaksiActionPerformed(evt);
            }
        });

        jLabel3.setText("Harga Sewa");

        jLabel10.setText("Nama Penyewa");

        jLabel11.setText("Tanggal Sewa");

        jLabel12.setText("No. Transaksi");

        text_nama_penyewa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                text_nama_penyewaKeyPressed(evt);
            }
        });

        jLabel14.setText("Uang bayar");

        jLabel16.setText("Kembalian");

        text_uang_bayar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                text_uang_bayarKeyPressed(evt);
            }
        });

        jLabel17.setText("No. kamar");

        text_no_kamar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                text_no_kamarKeyPressed(evt);
            }
        });

        text_id_penyewa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_id_penyewaActionPerformed(evt);
            }
        });

        simpan.setText("Simpan");
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });

        delete.setText("Hapus");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        cetak.setText("Cetak");
        cetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cetakActionPerformed(evt);
            }
        });

        tambah.setText("Tambah");
        tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahActionPerformed(evt);
            }
        });

        jLabel13.setText("Id Penyewa");

        text_status.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                text_statusKeyPressed(evt);
            }
        });

        jLabel2.setText("Status");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel10)
                    .addComponent(jLabel13)
                    .addComponent(jLabel17)
                    .addComponent(jLabel2))
                .addGap(19, 19, 19)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(text_no_transaksi, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                    .addComponent(text_nama_penyewa)
                    .addComponent(text_id_penyewa)
                    .addComponent(text_no_kamar)
                    .addComponent(text_status))
                .addGap(26, 26, 26)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                            .addComponent(jLabel11)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGap(19, 19, 19)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(text_tanggal_sewa, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                    .addComponent(text_harga)
                    .addComponent(text_uang_bayar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(text_kembalian))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cetak, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(tambah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(simpan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 13, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(tambah)
                        .addGap(6, 6, 6)
                        .addComponent(simpan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(delete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cetak))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12)
                                    .addComponent(text_no_transaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(text_nama_penyewa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)
                                    .addComponent(text_harga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(text_tanggal_sewa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(text_id_penyewa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17)
                                    .addComponent(text_no_kamar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel16)
                                        .addComponent(text_kembalian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(text_status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)))
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel14)
                                .addComponent(text_uang_bayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Tabel Data Penyewaan"));

        tabel_penyewaan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel_penyewaan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_penyewaanMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabel_penyewaan);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 649, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Data Penyewaan", jPanel2);

        tabel_cari_penyewaan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabel_cari_penyewaan);

        text_cari_penyewaan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                text_cari_penyewaanKeyPressed(evt);
            }
        });

        jLabel8.setText("Cari Data Penyewaan");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 667, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(text_cari_penyewaan, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_cari_penyewaan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(238, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Cari Data", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 692, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 480, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void text_no_transaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_no_transaksiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_no_transaksiActionPerformed

    private void text_id_penyewaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_id_penyewaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_id_penyewaActionPerformed

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        // TODO add your handling code here:
        String no_transaksi,nama_penyewa,nama_penyewa1 = null,nama_penyewa2 = null,id_penyewa,id_penyewa1 = null,id_penyewa2 = null,no_kamar,status,harga_sewa,uang_bayar,kembalian,cari;
        java.util.Date tanggal_sewa;
        no_transaksi = text_no_transaksi.getText();
        id_penyewa = text_id_penyewa.getText();
        nama_penyewa = text_nama_penyewa.getText();
        no_kamar = text_no_kamar.getText();
        status = text_status.getText();
        tanggal_sewa = (java.util.Date) this.text_tanggal_sewa.getDate();
        harga_sewa = text_harga.getText();
        uang_bayar = text_uang_bayar.getText();
        kembalian = text_kembalian.getText();
        Connection conn = DatabaseConnectivity.getConnection();
        cari = text_id_penyewa.getText();
        if("".equals(cari)){
             cari="#";
        }
        try{           
            String sql="Select id_penyewa,nama_penyewa from penyewaan where "
                    + "id_penyewa='"+cari+"' "
                    + "order by id_penyewa asc";
            java.sql.Statement stmt=conn.createStatement();
            java.sql.ResultSet rslt=stmt.executeQuery(sql);
            while(rslt.next()){
                id_penyewa1 = rslt.getString("id_penyewa");
                id_penyewa2=id_penyewa1;
                nama_penyewa1 =rslt.getString("nama_penyewa");
                nama_penyewa2=nama_penyewa1;
            }          
            text_dummy.setText(id_penyewa2);
            text_dummy1.setText(nama_penyewa2);
        }catch(SQLException | HeadlessException ex){
        }
        String id_penyewa3 = text_dummy.getText();
        String nama_penyewa3 = text_dummy1.getText();
        if(status.compareTo("Terisi")==0 && id_penyewa.compareTo(id_penyewa3)!=0){
            JOptionPane.showMessageDialog(null, "Maaf, kamar telah terisi oleh seseorang ! (silakan cari kamar yg lain)","Informasi", JOptionPane.INFORMATION_MESSAGE);
            text_no_kamar.setText("");
            text_status.setText("");
            text_harga.setText("");
            text_uang_bayar.setText("");
            text_kembalian.setText("");
            text_no_kamar.requestFocus();
        }else if (id_penyewa.compareTo("")==0){
            JOptionPane.showMessageDialog(null, "Silahkan isi NAMA PENYEWA!","Informasi", JOptionPane.INFORMATION_MESSAGE);
            text_nama_penyewa.requestFocus();
        }else if (nama_penyewa.compareTo("")==0){
            JOptionPane.showMessageDialog(null, "Silahkan isi NAMA PENYEWA!","Informasi", JOptionPane.INFORMATION_MESSAGE);
            text_nama_penyewa.requestFocus();
        }else if (status.compareTo("")==0){
            JOptionPane.showMessageDialog(null, "Silahkan isi NOMOR KAMAR!","Informasi", JOptionPane.INFORMATION_MESSAGE);
            text_no_kamar.requestFocus();
        }else if (no_kamar.compareTo("")==0){
            JOptionPane.showMessageDialog(null, "Silahkan isi NOMOR KAMAR!","Informasi", JOptionPane.INFORMATION_MESSAGE);
            text_no_kamar.requestFocus();
        }else if(tanggal_sewa==null){
            JOptionPane.showMessageDialog(null, "Silahkan isi TANGGAL SEWA!","Informasi", JOptionPane.INFORMATION_MESSAGE);
            text_tanggal_sewa.requestFocus();
        }else if(uang_bayar.compareTo("")==0){
            JOptionPane.showMessageDialog(null, "Silahkan isi UANG BAYAR!","Informasi", JOptionPane.INFORMATION_MESSAGE);
            text_uang_bayar.requestFocus();
        }else  {
            try {
                String sql = "insert into penyewaan values (?,?,?,?,?,?)";
                PreparedStatement stat = (PreparedStatement) conn.prepareStatement(sql);
                stat.setString(1, no_transaksi);
                stat.setString(2, id_penyewa);
                stat.setString(3, nama_penyewa);
                stat.setString(4, no_kamar);
                stat.setDate(5, new java.sql.Date(tanggal_sewa.getTime()));
                stat.setString(6, harga_sewa);
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "Menyimpan data BERHASIL","Informasi", JOptionPane.INFORMATION_MESSAGE);
                reset();
                tampil_tabel_penyewaan();
                text_no_transaksi.setEnabled(false);
                text_nama_penyewa.setEnabled(false);
                text_id_penyewa.setEnabled(false);
                text_no_kamar.setEnabled(false);
                text_status.setEnabled(false);
                text_tanggal_sewa.setEnabled(false);
                text_harga.setEnabled(false);
                text_uang_bayar.setEnabled(false);
                text_kembalian.setEnabled(false);
                tambah.setEnabled(true);
                simpan.setEnabled(false);
                cancel.setEnabled(false);
                delete.setEnabled(false);
                cetak.setEnabled(true);
            }catch (SQLException | HeadlessException ex){
                JOptionPane.showMessageDialog(null, "Menyimpan data GAGAL","Informasi", JOptionPane.INFORMATION_MESSAGE);
            }
            
            try {
                String status1 = "Terisi";
                String sql="update kamar set status=? where no_kamar='"+no_kamar+"'";
                PreparedStatement stat = (PreparedStatement) conn.prepareStatement(sql);
                stat.setString(1, status1);
                stat.executeUpdate();
            }catch(SQLException se){
                JOptionPane.showMessageDialog(null, "Menyimpan data GAGAL","Informasi", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_simpanActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        int baris = tabel_penyewaan.getSelectedRow();
        String no_transaksi = tabmode.getValueAt(baris, 0).toString();
        int ok=JOptionPane.showConfirmDialog(null,"Apakah Anda yakin ingin menghapus data penyewaan dengan kode pinjam : "+no_transaksi+"?","Konfirmasi",JOptionPane.YES_NO_OPTION);
        if(ok==0){
            try{
                //panggil method koneksi
                Connection conn = DatabaseConnectivity.getConnection();
                String sql="delete from penyewaan where no_transaksi='"+no_transaksi+"'";
                Statement st = conn.createStatement();
                st.executeUpdate(sql);
                JOptionPane.showMessageDialog(null,"Data Berhasil di hapus");
                reset();
                tampil_tabel_penyewaan();
                text_no_transaksi.setEnabled(false);
                text_nama_penyewa.setEnabled(false);
                text_id_penyewa.setEnabled(false);
                text_no_kamar.setEnabled(false);
                text_status.setEnabled(false);
                text_tanggal_sewa.setEnabled(false);
                text_harga.setEnabled(false);
                text_uang_bayar.setEnabled(false);
                text_kembalian.setEnabled(false);
                simpan.setEnabled(false);
                cancel.setEnabled(false);
                delete.setEnabled(false);
                cetak.setEnabled(true);
                tambah.setEnabled(true);
            }catch(SQLException | HeadlessException e){
                JOptionPane.showMessageDialog(null,"Data Gagal di hapus");
            }
        }
    }//GEN-LAST:event_deleteActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // TODO add your handling code here:
        reset();
        text_no_transaksi.setEnabled(false);
        text_nama_penyewa.setEnabled(false);
        text_id_penyewa.setEnabled(false);
        text_no_kamar.setEnabled(false);
        text_status.setEnabled(false);
        text_tanggal_sewa.setEnabled(false);
        text_harga.setEnabled(false);
        text_uang_bayar.setEnabled(false);
        text_kembalian.setEnabled(false);
        tambah.setEnabled(true);
        simpan.setEnabled(false);
        cancel.setEnabled(false);
        delete.setEnabled(false);
        cetak.setEnabled(true);
    }//GEN-LAST:event_cancelActionPerformed

    private void cetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cetakActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cetakActionPerformed

    private void tabel_penyewaanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_penyewaanMouseClicked
        // TODO add your handling code here:
        reset();
        text_no_transaksi.setEnabled(false);
        text_nama_penyewa.setEnabled(false);
        text_id_penyewa.setEnabled(false);
        text_no_kamar.setEnabled(false);
        text_status.setEnabled(false);
        text_tanggal_sewa.setEnabled(false);
        text_harga.setEnabled(false);
        text_uang_bayar.setEnabled(false);
        text_kembalian.setEnabled(false);
        int baris = tabel_penyewaan.getSelectedRow();
        text_no_transaksi.setText((String)tabel_penyewaan.getValueAt(baris, 0));
        text_id_penyewa.setText((String)tabel_penyewaan.getValueAt(baris, 1));
        text_nama_penyewa.setText((String)tabel_penyewaan.getValueAt(baris, 2));
        text_no_kamar.setText((String)tabel_penyewaan.getValueAt(baris, 3));
        text_harga.setText((String)tabel_penyewaan.getValueAt(baris, 5));
        
        cancel.setEnabled(true);
        simpan.setEnabled(false);
        delete.setEnabled(true);
        tambah.setEnabled(false);

    }//GEN-LAST:event_tabel_penyewaanMouseClicked

    private void text_cari_penyewaanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_cari_penyewaanKeyPressed
        // TODO add your handling code here:
        String cari = text_cari_penyewaan.getText();
        Object []baris = {"No. Transaksi","Id Penyewa","Nama Penyewa","No. Kamar","Tanggal Sewa","Harga Sewa"};
        tabmode = new DefaultTableModel(null, baris);
        tabel_cari_penyewaan.setModel(tabmode);

        //panggil method koneksi
        Connection conn = DatabaseConnectivity.getConnection();

        //untuk menampilkan di table
        try{
            String sql="Select * from penyewaan where "
            + "no_transaksi like '%"+cari+"%' "
            + "OR id_penyewa like '%"+cari+"%' "
            + "OR nama_penyewa like '%"+cari+"%' "
            + "OR no_kamar like '%"+cari+"%' "
            + "OR tanggal_sewa like '%"+cari+"%' "
            + "OR total_bayar like '%"+cari+"%' "
            + "order by no_kamar asc";
            java.sql.Statement stmt=conn.createStatement();
            java.sql.ResultSet hasil=stmt.executeQuery(sql);
            while(hasil.next()){
                String no_transaksi = hasil.getString("no_transaksi");
                String id_penyewa = hasil.getString("id_penyewa");
                String nama_penyewa = hasil.getString("nama_penyewa");
                String no_kamar = hasil.getString("no_kamar");
                String tanggal_sewa = hasil.getString("tanggal_sewa"); 
                String total_bayar = hasil.getString("total_bayar");
                String[] data = {no_transaksi, id_penyewa, nama_penyewa, no_kamar, tanggal_sewa, total_bayar};
                tabmode.addRow(data);
            }
        }
        catch(Exception ex){
        }
    }//GEN-LAST:event_text_cari_penyewaanKeyPressed

    private void jTabbedPane2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane2MouseClicked
        // TODO add your handling code here:
        tampil_tabel_penyewaan();
        tampil_tabel_cari_penyewaan();
    }//GEN-LAST:event_jTabbedPane2MouseClicked

    private void tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahActionPerformed
        // TODO add your handling code here:
        String kode_sewa = "S";
        String nomor_transaksi1 = null;
        String tahun = null;
        String kosong = null;
        Connection conn = DatabaseConnectivity.getConnection();
        try {
            Calendar cal = Calendar.getInstance();
            int year = cal.get(Calendar.YEAR);
            tahun = String.valueOf(year);
            String sql = "select no_transaksi,year(now()) as tahun from penyewaan order by no_transaksi asc";
            java.sql.Statement stat = conn.createStatement();
            java.sql.ResultSet hasil = stat.executeQuery(sql);
            while (hasil.next()){
                String nomor_transaksi = hasil.getString("no_transaksi");
                nomor_transaksi1 = nomor_transaksi;
                String tahun1 = hasil.getString("tahun");
            }
            if(nomor_transaksi1==null){
                nomor_transaksi1="S0000000";
            }
            String sub_nomor = nomor_transaksi1.substring(5,8);
            int sub_nomor1 = Integer.parseInt(sub_nomor);
            sub_nomor = String.valueOf(sub_nomor1);
            int panjang = sub_nomor.length();
            switch (panjang) {
                case 1:
                    kosong = "00";
                    break;
                case 2:
                    kosong = "0";
                    break;
                case 3:
                    kosong = null;
                    break;
                default:
                    break;
            }
            sub_nomor1=sub_nomor1+1;
            sub_nomor=String.valueOf(sub_nomor1);
            text_no_transaksi.setText(kode_sewa+tahun+kosong+sub_nomor);
        } catch (SQLException | NumberFormatException e) {
        }
        text_no_transaksi.setEnabled(false);
        text_nama_penyewa.setEnabled(true);
        text_id_penyewa.setEnabled(false);
        text_no_kamar.setEnabled(true);
        text_tanggal_sewa.setEnabled(true);
        text_harga.setEnabled(false);
        text_uang_bayar.setEnabled(true);
        text_kembalian.setEnabled(false);
        tambah.setEnabled(false);
        simpan.setEnabled(true);
        cancel.setEnabled(true);
        delete.setEnabled(false);
        cetak.setEnabled(true);
    }//GEN-LAST:event_tambahActionPerformed

    private void text_nama_penyewaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_nama_penyewaKeyPressed
        // TODO add your handling code here:
        String nama_penyewa = null,id_penyewa = null;
        String cari = text_nama_penyewa.getText();
        if("".equals(cari)){
             cari="#";
        }
        Connection conn = DatabaseConnectivity.getConnection();
        try{           
            String sql="Select id_penyewa,nama_penyewa from penyewa where "
                    + "nama_penyewa='"+cari+"' "
                    + "order by id_penyewa asc";
            java.sql.Statement stmt=conn.createStatement();
            java.sql.ResultSet rslt=stmt.executeQuery(sql);
            while(rslt.next()){
                id_penyewa = rslt.getString("id_penyewa");
                nama_penyewa = rslt.getString("nama_penyewa");
            }          
            if(nama_penyewa==null){
                text_id_penyewa.setText("");
                if (evt.getKeyCode() == KeyEvent.VK_ENTER) {     
                    JOptionPane.showMessageDialog(null,"Data PENYEWA tidak ditemukan!");
                }
            }else{
                text_id_penyewa.setText(id_penyewa);
                if (evt.getKeyCode() == KeyEvent.VK_ENTER) {     
                    JOptionPane.showMessageDialog(null,"Data PENYEWA ditemukan!");
                }
                text_no_kamar.requestFocus();
            }
        }catch(SQLException | HeadlessException ex){
        }
    }//GEN-LAST:event_text_nama_penyewaKeyPressed

    private void text_no_kamarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_no_kamarKeyPressed
        // TODO add your handling code here:
        String nomor_kamar = null,harga = null,status=null;
        String cari = text_no_kamar.getText();
        if("".equals(cari)){
             cari="#";
        }
        Connection conn = DatabaseConnectivity.getConnection();
        try{           
            String sql="Select no_kamar,harga,status from kamar where "
                    + "no_kamar='"+cari+"' "
                    + "order by no_kamar asc";
            java.sql.Statement stmt=conn.createStatement();
            java.sql.ResultSet rslt=stmt.executeQuery(sql);
            while(rslt.next()){
                nomor_kamar = rslt.getString("no_kamar");
                harga = rslt.getString("harga");
                status = rslt.getString("status");
            }          
            if(nomor_kamar==null){
                text_harga.setText("");
                text_status.setText("");
                if (evt.getKeyCode() == KeyEvent.VK_ENTER) {     
                    JOptionPane.showMessageDialog(null,"Data KAMAR tidak ditemukan!");
                }
            }else{
                text_harga.setText(harga);
                text_status.setText(status);
                if (evt.getKeyCode() == KeyEvent.VK_ENTER) {     
                    JOptionPane.showMessageDialog(null,"Data KAMAR ditemukan!");
                }
                text_tanggal_sewa.requestFocus();
            }
        }catch(SQLException | HeadlessException ex){
        }
    }//GEN-LAST:event_text_no_kamarKeyPressed

    private void text_uang_bayarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_uang_bayarKeyPressed
        // TODO add your handling code here:
        String harga,uang_bayar;
        harga = text_harga.getText();
        uang_bayar = text_uang_bayar.getText();
        int harga1 = Integer.parseInt(harga);
        int uang_bayar1 = Integer.parseInt(uang_bayar);
        int kembalian = uang_bayar1-harga1;
        if(kembalian<0){
            kembalian = 0;
        }
        String kembalian1=String.valueOf(kembalian);
        text_kembalian.setText(kembalian1);
    }//GEN-LAST:event_text_uang_bayarKeyPressed

    private void text_statusKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_statusKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_statusKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPenyewaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPenyewaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPenyewaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPenyewaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FormPenyewaan dialog = new FormPenyewaan(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel;
    private javax.swing.JButton cetak;
    private javax.swing.JButton delete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JButton simpan;
    private javax.swing.JTable tabel_cari_penyewaan;
    private javax.swing.JTable tabel_penyewaan;
    private javax.swing.JButton tambah;
    private javax.swing.JTextField text_cari_penyewaan;
    private javax.swing.JTextField text_dummy;
    private javax.swing.JTextField text_dummy1;
    private javax.swing.JTextField text_harga;
    private javax.swing.JTextField text_id_penyewa;
    private javax.swing.JTextField text_kembalian;
    private javax.swing.JTextField text_nama_penyewa;
    private javax.swing.JTextField text_no_kamar;
    private javax.swing.JTextField text_no_transaksi;
    private javax.swing.JTextField text_status;
    private com.toedter.calendar.JDateChooser text_tanggal_sewa;
    private javax.swing.JTextField text_uang_bayar;
    // End of variables declaration//GEN-END:variables
}
