/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package id.ac.pos.gudang.Panel;

import id.ac.pos.gudang.Dialog.DialogTambahPemesanan;
import javax.swing.JDialog;
import id.ac.pos.gudang.Form.FormHome;
import id.ac.pos.gudang.dao.PemesananDAO;
import id.ac.pos.gudang.daoimpl.PemesananDAOImpl;
import id.ac.pos.gudang.entity.Pemesanan;
import id.ac.pos.gudang.tablemodel.PemesananTM;
import java.util.ArrayList;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author reyha
 */
public class PanelPemesanan extends javax.swing.JPanel {

    /**
     * Creates new form PanelPemesanan
     */
    
    private Pemesanan pemesanan;
    private PemesananDAO dao;
    ArrayList<Pemesanan> arrayPemesanan;
    TableRowSorter sorter;
    
    public PanelPemesanan() {
        initComponents();
        getDataPrangko();
        getDataDokumenFilateli();
        getDataKemasan();
        getDataMerchandise();
        getDataMS_SS();
        getDataPrisma();
        getDataSHP_SHPSS();
    }

    
    private void getDataPrangko(){
        dao = new PemesananDAOImpl();
        arrayPemesanan = dao.getDataPemesananPrangko();

        PemesananTM pemesananTableModel = new PemesananTM();
        pemesananTableModel.setDataPemesanan(arrayPemesanan);
        sorter = new TableRowSorter(pemesananTableModel);
        tablePemesananPrangko.setRowSorter(sorter);
        tablePemesananPrangko.setModel(pemesananTableModel);
    }
    
    private void getDataMS_SS(){
        dao = new PemesananDAOImpl();
        arrayPemesanan = dao.getDataPemesananMS_SS();

        PemesananTM pemesananTableModel = new PemesananTM();
        pemesananTableModel.setDataPemesanan(arrayPemesanan);
        sorter = new TableRowSorter(pemesananTableModel);
        tablePemesananMS_SS.setRowSorter(sorter);
        tablePemesananMS_SS.setModel(pemesananTableModel);
    }
    
    private void getDataKemasan(){
        dao = new PemesananDAOImpl();
        arrayPemesanan = dao.getDataPemesananKemasan();

        PemesananTM pemesananTableModel = new PemesananTM();
        pemesananTableModel.setDataPemesanan(arrayPemesanan);
        sorter = new TableRowSorter(pemesananTableModel);
        tablePemesananKemasan.setRowSorter(sorter);
        tablePemesananKemasan.setModel(pemesananTableModel);
    }
    
    private void getDataMerchandise(){
        dao = new PemesananDAOImpl();
        arrayPemesanan = dao.getDataPemesananMerchandise();

        PemesananTM pemesananTableModel = new PemesananTM();
        pemesananTableModel.setDataPemesanan(arrayPemesanan);
        sorter = new TableRowSorter(pemesananTableModel);
        tablePemesananMerchandise.setRowSorter(sorter);
        tablePemesananMerchandise.setModel(pemesananTableModel);
    }
    
    private void getDataPrisma(){
        dao = new PemesananDAOImpl();
        arrayPemesanan = dao.getDataPemesananPrisma();

        PemesananTM pemesananTableModel = new PemesananTM();
        pemesananTableModel.setDataPemesanan(arrayPemesanan);
        sorter = new TableRowSorter(pemesananTableModel);
        tablePemesananPrisma.setRowSorter(sorter);
        tablePemesananPrisma.setModel(pemesananTableModel);
    }
    
    private void getDataDokumenFilateli(){
        dao = new PemesananDAOImpl();
        arrayPemesanan = dao.getDataPemesananDokumenFilateli();

        PemesananTM pemesananTableModel = new PemesananTM();
        pemesananTableModel.setDataPemesanan(arrayPemesanan);
        sorter = new TableRowSorter(pemesananTableModel);
        tablePemesananDokumenFilateli.setRowSorter(sorter);
        tablePemesananDokumenFilateli.setModel(pemesananTableModel);
    }
    
    private void getDataSHP_SHPSS(){
        dao = new PemesananDAOImpl();
        arrayPemesanan = dao.getDataPemesananSHP_SHPSS();

        PemesananTM pemesananTableModel = new PemesananTM();
        pemesananTableModel.setDataPemesanan(arrayPemesanan);
        sorter = new TableRowSorter(pemesananTableModel);
        tablePemesananSHP_SHPSS.setRowSorter(sorter);
        tablePemesananSHP_SHPSS.setModel(pemesananTableModel);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane6 = new javax.swing.JTabbedPane();
        Prangko4 = new javax.swing.JPanel();
        jPanel52 = new javax.swing.JPanel();
        jScrollPane17 = new javax.swing.JScrollPane();
        tablePemesananPrangko = new javax.swing.JTable();
        buttonCariPrangko30 = new javax.swing.JButton();
        fieldCariPrangko30 = new javax.swing.JTextField();
        comboCariPrangko30 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        MS_SS4 = new javax.swing.JPanel();
        jPanel54 = new javax.swing.JPanel();
        jScrollPane18 = new javax.swing.JScrollPane();
        tablePemesananMS_SS = new javax.swing.JTable();
        buttonCariPrangko31 = new javax.swing.JButton();
        fieldCariPrangko31 = new javax.swing.JTextField();
        comboCariPrangko31 = new javax.swing.JComboBox<>();
        Kemasan4 = new javax.swing.JPanel();
        jPanel55 = new javax.swing.JPanel();
        jScrollPane19 = new javax.swing.JScrollPane();
        tablePemesananKemasan = new javax.swing.JTable();
        buttonCariPrangko32 = new javax.swing.JButton();
        fieldCariPrangko32 = new javax.swing.JTextField();
        comboCariPrangko32 = new javax.swing.JComboBox<>();
        Merchandise4 = new javax.swing.JPanel();
        jPanel56 = new javax.swing.JPanel();
        jScrollPane20 = new javax.swing.JScrollPane();
        tablePemesananMerchandise = new javax.swing.JTable();
        buttonCariPrangko33 = new javax.swing.JButton();
        fieldCariPrangko33 = new javax.swing.JTextField();
        comboCariPrangko33 = new javax.swing.JComboBox<>();
        Prisma4 = new javax.swing.JPanel();
        jPanel57 = new javax.swing.JPanel();
        jScrollPane21 = new javax.swing.JScrollPane();
        tablePemesananPrisma = new javax.swing.JTable();
        buttonCariPrangko34 = new javax.swing.JButton();
        fieldCariPrangko34 = new javax.swing.JTextField();
        comboCariPrangko34 = new javax.swing.JComboBox<>();
        DokumenFilateli4 = new javax.swing.JPanel();
        jPanel58 = new javax.swing.JPanel();
        jScrollPane22 = new javax.swing.JScrollPane();
        tablePemesananDokumenFilateli = new javax.swing.JTable();
        buttonCariPrangko35 = new javax.swing.JButton();
        fieldCariPrangko35 = new javax.swing.JTextField();
        comboCariPrangko35 = new javax.swing.JComboBox<>();
        SHP_SHPSS4 = new javax.swing.JPanel();
        jPanel59 = new javax.swing.JPanel();
        jScrollPane23 = new javax.swing.JScrollPane();
        tablePemesananSHP_SHPSS = new javax.swing.JTable();
        buttonCariPrangko36 = new javax.swing.JButton();
        fieldCariPrangko36 = new javax.swing.JTextField();
        comboCariPrangko36 = new javax.swing.JComboBox<>();

        jTabbedPane6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane6MouseClicked(evt);
            }
        });

        Prangko4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Prangko4MouseClicked(evt);
            }
        });

        jPanel52.setBorder(javax.swing.BorderFactory.createTitledBorder("Tabel Data Pemesanan"));

        tablePemesananPrangko.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablePemesananPrangko.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablePemesananPrangkoMouseClicked(evt);
            }
        });
        jScrollPane17.setViewportView(tablePemesananPrangko);

        buttonCariPrangko30.setText("Cari");
        buttonCariPrangko30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCariPrangko30ActionPerformed(evt);
            }
        });

        fieldCariPrangko30.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fieldCariPrangko30MouseClicked(evt);
            }
        });

        comboCariPrangko30.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nama Produk", "Id Produk", "Nominal", "Biaya Cetak", "Stok", "Tahun" }));

        javax.swing.GroupLayout jPanel52Layout = new javax.swing.GroupLayout(jPanel52);
        jPanel52.setLayout(jPanel52Layout);
        jPanel52Layout.setHorizontalGroup(
            jPanel52Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel52Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(comboCariPrangko30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldCariPrangko30, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonCariPrangko30))
            .addComponent(jScrollPane17, javax.swing.GroupLayout.DEFAULT_SIZE, 975, Short.MAX_VALUE)
        );
        jPanel52Layout.setVerticalGroup(
            jPanel52Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel52Layout.createSequentialGroup()
                .addGroup(jPanel52Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonCariPrangko30)
                    .addComponent(fieldCariPrangko30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboCariPrangko30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane17, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE))
        );

        jButton1.setText("Tambah Pemesanan");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Prangko4Layout = new javax.swing.GroupLayout(Prangko4);
        Prangko4.setLayout(Prangko4Layout);
        Prangko4Layout.setHorizontalGroup(
            Prangko4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel52, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Prangko4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
        Prangko4Layout.setVerticalGroup(
            Prangko4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Prangko4Layout.createSequentialGroup()
                .addComponent(jPanel52, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane6.addTab("Prangko", Prangko4);

        MS_SS4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MS_SS4MouseClicked(evt);
            }
        });

        jPanel54.setBorder(javax.swing.BorderFactory.createTitledBorder("Tabel Data Pemesanan"));

        tablePemesananMS_SS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablePemesananMS_SS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablePemesananMS_SSMouseClicked(evt);
            }
        });
        jScrollPane18.setViewportView(tablePemesananMS_SS);

        buttonCariPrangko31.setText("Cari");
        buttonCariPrangko31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCariPrangko31ActionPerformed(evt);
            }
        });

        fieldCariPrangko31.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fieldCariPrangko31MouseClicked(evt);
            }
        });

        comboCariPrangko31.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nama Produk", "Id Produk", "Nominal", "Biaya Cetak", "Stok", "Tahun" }));

        javax.swing.GroupLayout jPanel54Layout = new javax.swing.GroupLayout(jPanel54);
        jPanel54.setLayout(jPanel54Layout);
        jPanel54Layout.setHorizontalGroup(
            jPanel54Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel54Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(comboCariPrangko31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldCariPrangko31, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonCariPrangko31))
            .addComponent(jScrollPane18, javax.swing.GroupLayout.DEFAULT_SIZE, 975, Short.MAX_VALUE)
        );
        jPanel54Layout.setVerticalGroup(
            jPanel54Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel54Layout.createSequentialGroup()
                .addGroup(jPanel54Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonCariPrangko31)
                    .addComponent(fieldCariPrangko31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboCariPrangko31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane18, javax.swing.GroupLayout.DEFAULT_SIZE, 431, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout MS_SS4Layout = new javax.swing.GroupLayout(MS_SS4);
        MS_SS4.setLayout(MS_SS4Layout);
        MS_SS4Layout.setHorizontalGroup(
            MS_SS4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel54, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        MS_SS4Layout.setVerticalGroup(
            MS_SS4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel54, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane6.addTab("MS & SS", MS_SS4);

        Kemasan4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Kemasan4MouseClicked(evt);
            }
        });

        jPanel55.setBorder(javax.swing.BorderFactory.createTitledBorder("Tabel Data Pemesanan"));

        tablePemesananKemasan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablePemesananKemasan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablePemesananKemasanMouseClicked(evt);
            }
        });
        jScrollPane19.setViewportView(tablePemesananKemasan);

        buttonCariPrangko32.setText("Cari");
        buttonCariPrangko32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCariPrangko32ActionPerformed(evt);
            }
        });

        fieldCariPrangko32.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fieldCariPrangko32MouseClicked(evt);
            }
        });

        comboCariPrangko32.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nama Produk", "Id Produk", "Nominal", "Biaya Cetak", "Stok", "Tahun" }));

        javax.swing.GroupLayout jPanel55Layout = new javax.swing.GroupLayout(jPanel55);
        jPanel55.setLayout(jPanel55Layout);
        jPanel55Layout.setHorizontalGroup(
            jPanel55Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel55Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(comboCariPrangko32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldCariPrangko32, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonCariPrangko32))
            .addComponent(jScrollPane19, javax.swing.GroupLayout.DEFAULT_SIZE, 975, Short.MAX_VALUE)
        );
        jPanel55Layout.setVerticalGroup(
            jPanel55Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel55Layout.createSequentialGroup()
                .addGroup(jPanel55Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonCariPrangko32)
                    .addComponent(fieldCariPrangko32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboCariPrangko32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane19, javax.swing.GroupLayout.DEFAULT_SIZE, 431, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout Kemasan4Layout = new javax.swing.GroupLayout(Kemasan4);
        Kemasan4.setLayout(Kemasan4Layout);
        Kemasan4Layout.setHorizontalGroup(
            Kemasan4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel55, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        Kemasan4Layout.setVerticalGroup(
            Kemasan4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel55, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane6.addTab("Kemasan", Kemasan4);

        jPanel56.setBorder(javax.swing.BorderFactory.createTitledBorder("Tabel Data Pemesanan"));

        tablePemesananMerchandise.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablePemesananMerchandise.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablePemesananMerchandiseMouseClicked(evt);
            }
        });
        jScrollPane20.setViewportView(tablePemesananMerchandise);

        buttonCariPrangko33.setText("Cari");
        buttonCariPrangko33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCariPrangko33ActionPerformed(evt);
            }
        });

        fieldCariPrangko33.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fieldCariPrangko33MouseClicked(evt);
            }
        });

        comboCariPrangko33.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nama Produk", "Id Produk", "Nominal", "Biaya Cetak", "Stok", "Tahun" }));

        javax.swing.GroupLayout jPanel56Layout = new javax.swing.GroupLayout(jPanel56);
        jPanel56.setLayout(jPanel56Layout);
        jPanel56Layout.setHorizontalGroup(
            jPanel56Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel56Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(comboCariPrangko33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldCariPrangko33, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonCariPrangko33))
            .addComponent(jScrollPane20, javax.swing.GroupLayout.DEFAULT_SIZE, 975, Short.MAX_VALUE)
        );
        jPanel56Layout.setVerticalGroup(
            jPanel56Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel56Layout.createSequentialGroup()
                .addGroup(jPanel56Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonCariPrangko33)
                    .addComponent(fieldCariPrangko33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboCariPrangko33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane20, javax.swing.GroupLayout.DEFAULT_SIZE, 431, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout Merchandise4Layout = new javax.swing.GroupLayout(Merchandise4);
        Merchandise4.setLayout(Merchandise4Layout);
        Merchandise4Layout.setHorizontalGroup(
            Merchandise4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel56, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        Merchandise4Layout.setVerticalGroup(
            Merchandise4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel56, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane6.addTab("Merchandise", Merchandise4);

        jPanel57.setBorder(javax.swing.BorderFactory.createTitledBorder("Tabel Data Pemesanan"));

        tablePemesananPrisma.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablePemesananPrisma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablePemesananPrismaMouseClicked(evt);
            }
        });
        jScrollPane21.setViewportView(tablePemesananPrisma);

        buttonCariPrangko34.setText("Cari");
        buttonCariPrangko34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCariPrangko34ActionPerformed(evt);
            }
        });

        fieldCariPrangko34.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fieldCariPrangko34MouseClicked(evt);
            }
        });

        comboCariPrangko34.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nama Produk", "Id Produk", "Nominal", "Biaya Cetak", "Stok", "Tahun" }));

        javax.swing.GroupLayout jPanel57Layout = new javax.swing.GroupLayout(jPanel57);
        jPanel57.setLayout(jPanel57Layout);
        jPanel57Layout.setHorizontalGroup(
            jPanel57Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel57Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(comboCariPrangko34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldCariPrangko34, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonCariPrangko34))
            .addComponent(jScrollPane21, javax.swing.GroupLayout.DEFAULT_SIZE, 975, Short.MAX_VALUE)
        );
        jPanel57Layout.setVerticalGroup(
            jPanel57Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel57Layout.createSequentialGroup()
                .addGroup(jPanel57Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonCariPrangko34)
                    .addComponent(fieldCariPrangko34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboCariPrangko34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane21, javax.swing.GroupLayout.DEFAULT_SIZE, 431, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout Prisma4Layout = new javax.swing.GroupLayout(Prisma4);
        Prisma4.setLayout(Prisma4Layout);
        Prisma4Layout.setHorizontalGroup(
            Prisma4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel57, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        Prisma4Layout.setVerticalGroup(
            Prisma4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel57, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane6.addTab("Prisma", Prisma4);

        jPanel58.setBorder(javax.swing.BorderFactory.createTitledBorder("Tabel Data Pemesanan"));

        tablePemesananDokumenFilateli.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablePemesananDokumenFilateli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablePemesananDokumenFilateliMouseClicked(evt);
            }
        });
        jScrollPane22.setViewportView(tablePemesananDokumenFilateli);

        buttonCariPrangko35.setText("Cari");
        buttonCariPrangko35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCariPrangko35ActionPerformed(evt);
            }
        });

        fieldCariPrangko35.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fieldCariPrangko35MouseClicked(evt);
            }
        });

        comboCariPrangko35.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nama Produk", "Id Produk", "Nominal", "Biaya Cetak", "Stok", "Tahun" }));

        javax.swing.GroupLayout jPanel58Layout = new javax.swing.GroupLayout(jPanel58);
        jPanel58.setLayout(jPanel58Layout);
        jPanel58Layout.setHorizontalGroup(
            jPanel58Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel58Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(comboCariPrangko35, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldCariPrangko35, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonCariPrangko35))
            .addComponent(jScrollPane22, javax.swing.GroupLayout.DEFAULT_SIZE, 975, Short.MAX_VALUE)
        );
        jPanel58Layout.setVerticalGroup(
            jPanel58Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel58Layout.createSequentialGroup()
                .addGroup(jPanel58Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonCariPrangko35)
                    .addComponent(fieldCariPrangko35, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboCariPrangko35, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane22, javax.swing.GroupLayout.DEFAULT_SIZE, 431, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout DokumenFilateli4Layout = new javax.swing.GroupLayout(DokumenFilateli4);
        DokumenFilateli4.setLayout(DokumenFilateli4Layout);
        DokumenFilateli4Layout.setHorizontalGroup(
            DokumenFilateli4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel58, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        DokumenFilateli4Layout.setVerticalGroup(
            DokumenFilateli4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel58, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane6.addTab("Dokumen Filateli", DokumenFilateli4);

        SHP_SHPSS4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SHP_SHPSS4MouseClicked(evt);
            }
        });

        jPanel59.setBorder(javax.swing.BorderFactory.createTitledBorder("Tabel Data Pemesanan"));

        tablePemesananSHP_SHPSS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablePemesananSHP_SHPSS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablePemesananSHP_SHPSSMouseClicked(evt);
            }
        });
        jScrollPane23.setViewportView(tablePemesananSHP_SHPSS);

        buttonCariPrangko36.setText("Cari");
        buttonCariPrangko36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCariPrangko36ActionPerformed(evt);
            }
        });

        fieldCariPrangko36.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fieldCariPrangko36MouseClicked(evt);
            }
        });

        comboCariPrangko36.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nama Produk", "Id Produk", "Nominal", "Biaya Cetak", "Stok", "Tahun" }));

        javax.swing.GroupLayout jPanel59Layout = new javax.swing.GroupLayout(jPanel59);
        jPanel59.setLayout(jPanel59Layout);
        jPanel59Layout.setHorizontalGroup(
            jPanel59Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel59Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(comboCariPrangko36, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldCariPrangko36, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonCariPrangko36))
            .addComponent(jScrollPane23, javax.swing.GroupLayout.DEFAULT_SIZE, 975, Short.MAX_VALUE)
        );
        jPanel59Layout.setVerticalGroup(
            jPanel59Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel59Layout.createSequentialGroup()
                .addGroup(jPanel59Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonCariPrangko36)
                    .addComponent(fieldCariPrangko36, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboCariPrangko36, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane23, javax.swing.GroupLayout.DEFAULT_SIZE, 431, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout SHP_SHPSS4Layout = new javax.swing.GroupLayout(SHP_SHPSS4);
        SHP_SHPSS4.setLayout(SHP_SHPSS4Layout);
        SHP_SHPSS4Layout.setHorizontalGroup(
            SHP_SHPSS4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel59, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        SHP_SHPSS4Layout.setVerticalGroup(
            SHP_SHPSS4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel59, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane6.addTab("SHP & SHPSS", SHP_SHPSS4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane6)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Prangko4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Prangko4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Prangko4MouseClicked

    private void MS_SS4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MS_SS4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_MS_SS4MouseClicked

    private void Kemasan4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Kemasan4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Kemasan4MouseClicked

    private void SHP_SHPSS4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SHP_SHPSS4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_SHP_SHPSS4MouseClicked

    private void jTabbedPane6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTabbedPane6MouseClicked

    private void tablePemesananPrangkoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablePemesananPrangkoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tablePemesananPrangkoMouseClicked

    private void buttonCariPrangko30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCariPrangko30ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonCariPrangko30ActionPerformed

    private void fieldCariPrangko30MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fieldCariPrangko30MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldCariPrangko30MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        FormHome formHome = new FormHome();
        boolean rootPaneCheckingEnabled = false;
        new DialogTambahPemesanan(formHome, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tablePemesananMS_SSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablePemesananMS_SSMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tablePemesananMS_SSMouseClicked

    private void buttonCariPrangko31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCariPrangko31ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonCariPrangko31ActionPerformed

    private void fieldCariPrangko31MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fieldCariPrangko31MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldCariPrangko31MouseClicked

    private void tablePemesananKemasanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablePemesananKemasanMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tablePemesananKemasanMouseClicked

    private void buttonCariPrangko32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCariPrangko32ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonCariPrangko32ActionPerformed

    private void fieldCariPrangko32MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fieldCariPrangko32MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldCariPrangko32MouseClicked

    private void tablePemesananMerchandiseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablePemesananMerchandiseMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tablePemesananMerchandiseMouseClicked

    private void buttonCariPrangko33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCariPrangko33ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonCariPrangko33ActionPerformed

    private void fieldCariPrangko33MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fieldCariPrangko33MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldCariPrangko33MouseClicked

    private void tablePemesananPrismaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablePemesananPrismaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tablePemesananPrismaMouseClicked

    private void buttonCariPrangko34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCariPrangko34ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonCariPrangko34ActionPerformed

    private void fieldCariPrangko34MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fieldCariPrangko34MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldCariPrangko34MouseClicked

    private void tablePemesananDokumenFilateliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablePemesananDokumenFilateliMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tablePemesananDokumenFilateliMouseClicked

    private void buttonCariPrangko35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCariPrangko35ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonCariPrangko35ActionPerformed

    private void fieldCariPrangko35MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fieldCariPrangko35MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldCariPrangko35MouseClicked

    private void tablePemesananSHP_SHPSSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablePemesananSHP_SHPSSMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tablePemesananSHP_SHPSSMouseClicked

    private void buttonCariPrangko36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCariPrangko36ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonCariPrangko36ActionPerformed

    private void fieldCariPrangko36MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fieldCariPrangko36MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldCariPrangko36MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DokumenFilateli4;
    private javax.swing.JPanel Kemasan4;
    private javax.swing.JPanel MS_SS4;
    private javax.swing.JPanel Merchandise4;
    private javax.swing.JPanel Prangko4;
    private javax.swing.JPanel Prisma4;
    private javax.swing.JPanel SHP_SHPSS4;
    private javax.swing.JButton buttonCariPrangko30;
    private javax.swing.JButton buttonCariPrangko31;
    private javax.swing.JButton buttonCariPrangko32;
    private javax.swing.JButton buttonCariPrangko33;
    private javax.swing.JButton buttonCariPrangko34;
    private javax.swing.JButton buttonCariPrangko35;
    private javax.swing.JButton buttonCariPrangko36;
    private javax.swing.JComboBox<String> comboCariPrangko30;
    private javax.swing.JComboBox<String> comboCariPrangko31;
    private javax.swing.JComboBox<String> comboCariPrangko32;
    private javax.swing.JComboBox<String> comboCariPrangko33;
    private javax.swing.JComboBox<String> comboCariPrangko34;
    private javax.swing.JComboBox<String> comboCariPrangko35;
    private javax.swing.JComboBox<String> comboCariPrangko36;
    private javax.swing.JTextField fieldCariPrangko30;
    private javax.swing.JTextField fieldCariPrangko31;
    private javax.swing.JTextField fieldCariPrangko32;
    private javax.swing.JTextField fieldCariPrangko33;
    private javax.swing.JTextField fieldCariPrangko34;
    private javax.swing.JTextField fieldCariPrangko35;
    private javax.swing.JTextField fieldCariPrangko36;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel52;
    private javax.swing.JPanel jPanel54;
    private javax.swing.JPanel jPanel55;
    private javax.swing.JPanel jPanel56;
    private javax.swing.JPanel jPanel57;
    private javax.swing.JPanel jPanel58;
    private javax.swing.JPanel jPanel59;
    private javax.swing.JScrollPane jScrollPane17;
    private javax.swing.JScrollPane jScrollPane18;
    private javax.swing.JScrollPane jScrollPane19;
    private javax.swing.JScrollPane jScrollPane20;
    private javax.swing.JScrollPane jScrollPane21;
    private javax.swing.JScrollPane jScrollPane22;
    private javax.swing.JScrollPane jScrollPane23;
    private javax.swing.JTabbedPane jTabbedPane6;
    private javax.swing.JTable tablePemesananDokumenFilateli;
    private javax.swing.JTable tablePemesananKemasan;
    private javax.swing.JTable tablePemesananMS_SS;
    private javax.swing.JTable tablePemesananMerchandise;
    private javax.swing.JTable tablePemesananPrangko;
    private javax.swing.JTable tablePemesananPrisma;
    private javax.swing.JTable tablePemesananSHP_SHPSS;
    // End of variables declaration//GEN-END:variables
}
